---

plugins:
  - jest
  - flowtype
  - babel

env:
  none: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommend'
  - 'plugin:flowtype/recommend'
  - 'plugin:lodash-fp/recommend'

rules:
  no-console: 0
